CREATE TABLE  USUARIO (
  ID_USUARIO SERIAL NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(32) NOT NULL UNIQUE,
	PASSWORD VARCHAR(32) NOT NULL
   )

CREATE TABLE EVENTO (
  ID_EVENTO SERIAL NOT NULL PRIMARY KEY,
  TIPO_EVENTO INTEGER NOT NULL,
  NOMBRE_EVENTO VARCHAR(32) NOT NULL,
  FECHA DATE NOT NULL,
  CONTENIDO VARCHAR(32) NOT NULL
)
 CREATE TABLE CASA (
   ID_CASA SERIAL NOT NULL PRIMARY KEY,
   NOMBRE_CASA VARCHAR(32) NOT NULL UNIQUE,
   DINERO_CASA INTEGER NOT NULL

 )

 CREATE TABLE RAZA (
    ID_RAZA SERIAL NOT NULL PRIMARY KEY,
    NOMBRE_RAZA VARCHAR(32) NOT NULL UNIQUE,
    CARACTERISTICAS VARCHAR(32) NOT NULL
 )

 CREATE TABLE PROFESION (
   ID_PROFESION SERIAL NOT NULL PRIMARY KEY,
   NOMBRE_PROFESION VARCHAR(32) NOT NULL UNIQUE,
   DESCRIPCION VARCHAR(1000) NOT NULL

 )

CREATE TABLE FEEDBACK(
  ID_FEEDBACK SERIAL NOT NULL PRIMARY KEY,
  COMENTARIO VARCHAR(100) NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  CONSTRAINT ID_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
)

CREATE TABLE PERSONAJE (
  ID_PERSONAJE SERIAL NOT NULL PRIMARY KEY,
  ID_CASA INTEGER,
  ID_RAZA INTEGER NOT NULL,
  ID_PROFESION INTEGER NOT NULL,
  NOMBRE_PERSONAJE VARCHAR(100) NOT NULL,
  DINERO_PERSONAJE INTEGER NOT NULL,
  FECHA_INI DATE,
  FECHA_FIN DATE,
  CONSTRAINT ID_CASA_FK FOREIGN KEY (ID_CASA) REFERENCES CASA(ID_CASA),
  CONSTRAINT ID_RAZA_FK FOREIGN KEY (ID_RAZA) REFERENCES RAZA(ID_RAZA),
  CONSTRAINT ID_PROFESION_FK FOREIGN KEY (ID_PROFESION) REFERENCES PROFESION(ID_PROFESION)
)

CREATE TABLE F_PERSONAJE (
  ID_F_PERSONAJE SERIAL NOT NULL PRIMARY KEY,
  VOTO_PERSONAJE BOOLEAN NOT NULL,
  ID_PERSONAJE INTEGER NOT NULL,
  ID_FEEDBACK INTEGER NOT NULL,
  CONSTRAINT ID_PERSONAJE_FK FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE),
  CONSTRAINT ID_FEEDBACK_FK FOREIGN KEY (ID_FEEDBACK) REFERENCES FEEDBACK(ID_FEEDBACK)
)

CREATE TABLE F_EVENTO (
  ID_F_EVENTO SERIAL NOT NULL PRIMARY KEY,
  VOTO_EVENTO BOOLEAN NOT NULL,
  ID_EVENTO INTEGER NOT NULL,
  ID_FEEDBACK INTEGER NOT NULL,
  CONSTRAINT ID_EVENTO_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
  CONSTRAINT ID_FEEDBACK_FK FOREIGN KEY (ID_FEEDBACK) REFERENCES FEEDBACK(ID_FEEDBACK)
)

CREATE TABLE EVENTO_PERSONAJE (
  ID_EVENTO INTEGER NOT NULL,
  ID_PERSONAJE INTEGER NOT NULL,
  CONSTRAINT ID_EVENTO_PERSONAJE_PK PRIMARY KEY (ID_EVENTO, ID_PERSONAJE),
  CONSTRAINT ID_EVENTO_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
  CONSTRAINT ID_PERSONAJE_FK FOREIGN KEY (ID_PERSONAJE) REFERENCES PERSONAJE(ID_PERSONAJE)
)

CREATE TABLE EVENTO_CASA (
  ID_EVENTO INTEGER NOT NULL,
  ID_CASA INTEGER NOT NULL,
  CONSTRAINT ID_EVENTO_CASA_PK PRIMARY KEY (ID_EVENTO, ID_CASA),
  CONSTRAINT ID_EVENTO_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
  CONSTRAINT ID_CASA_FK FOREIGN KEY (ID_CASA) REFERENCES CASA(ID_CASA)
)

CREATE TABLE R_RAZA_RAZA (
  ID_RAZA1 INTEGER NOT NULL,
  ID_RAZA2 INTEGER NOT NULL,
  CONSTRAINT ID_RAZA_RAZA_PK PRIMARY KEY (ID_RAZA1, ID_RAZA2),
  CONSTRAINT ID_RAZA1_FK FOREIGN KEY (ID_RAZA1) REFERENCES RAZA(ID_RAZA),
  CONSTRAINT ID_RAZA2_FK FOREIGN KEY (ID_RAZA2) REFERENCES RAZA(ID_RAZA),
  TIPO_RELACION INTEGER NOT NULL
)

CREATE TABLE R_PERSONAJE_PERSONAJE (
  ID_PERSONAJE1 INTEGER NOT NULL,
  ID_PERSONAJE2 INTEGER NOT NULL,
  CONSTRAINT ID_PERSONAJE_PERSONAJE_PK PRIMARY KEY (ID_PERSONAJE1, ID_PERSONAJE2),
  CONSTRAINT ID_PERSONAJE1_FK FOREIGN KEY (ID_PERSONAJE1) REFERENCES PERSONAJE(ID_PERSONAJE),
  CONSTRAINT ID_PERSONAJE2_FK FOREIGN KEY (ID_PERSONAJE2) REFERENCES PERSONAJE(ID_PERSONAJE),
  TIPO_RELACION INTEGER NOT NULL
)

CREATE TABLE R_CASA_CASA (
  ID_CASA1 INTEGER NOT NULL,
  ID_CASA2 INTEGER NOT NULL,
  CONSTRAINT ID_CASA_CASA_PK PRIMARY KEY (ID_CASA1, ID_CASA2),
  CONSTRAINT ID_CASA1_FK FOREIGN KEY (ID_CASA1) REFERENCES CASA(ID_CASA),
  CONSTRAINT ID_CASA2_FK FOREIGN KEY (ID_CASA2) REFERENCES CASA(ID_CASA),
  TIPO_RELACION INTEGER NOT NULL
)

CREATE TABLE TRANSACCION_BANCARIA (
  ID_CASA INTEGER NOT NULL,
  ID_TRANSACCION SERIAL NOT NULL PRIMARY KEY,
  CONSTRAINT ID_CASA_FK FOREIGN KEY (ID_CASA) REFERENCES CASA(ID_CASA),
  MONTO INTEGER NOT NULL,
  FECHA DATE NOT NULL
)
CREATE OR REPLACE VIEW view_evento_casa_personaje AS
 SELECT evento.nombre_evento,
    casa.nombre_casa,
    personaje.nombre_personaje
   FROM evento,
    casa,
    evento_casa,
    personaje,
    evento_personaje
  WHERE evento.id_evento = evento_casa.id_evento AND evento_casa.id_casa = casa.id_casa AND evento.id_evento = evento_personaje.id_evento AND evento_personaje.id_personaje = personaje.id_personaje;
